module.exports = {
  about: [
    "How Airbnb works",
    "Newsroom",
    "Airbnb 2021",
    "Investors",
    "Airbnb Plus",
    "Airbnb Luxe",
    "HotelTonight",
    "Airbnb for Work",
    "Made possible by Hosts",
    "Careers",
    "Founders' Letter",
  ],
  community: [
    "Diversity & Belonging",
    "Against Discrimination",
    "Accessibility",
    "Airbnb Associates",
    "Frontline Stays",
    "Guest Referrals",
    "Gift Cards",
    "Airbnb.org",
  ],
  host: [
    "Host your home",
    "Host an Online Experience",
    "Host an Experience",
    "Responsible Hosting",
    "Refer hosts",
    "Resource Centers",
    "Community Center",
  ],
  support: [
    "Our COVID-19 Response",
    "Help Center",
    "Cancellation options",
    "Neighborhood Support",
    "Trust & Safety",
  ],
};
